### ISSUE TITLE
Some icons has zero size

### ISSUE THREAD

**Issue by newsiberian** [franksouza183/EvolvereSuit#103]
Hello, Frank, please check this icon list:

> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/actions/12/transform-affect-gradient.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/actions/12/transform-affect-pattern.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/actions/12/transform-affect-rounded-corners.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/actions/12/transform-affect-stroke.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/actions/16/ubuntustudio-publishing.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-default.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-downloads.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-favorite.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-readonly.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-shared.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-symbolic-link.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-syncing.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-system.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-unreadable.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-warning.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/22/emblem-web.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-default.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-downloads.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-favorite.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-mounted.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-readonly.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-shared.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-symbolic-link.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-syncing.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-system.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-unmounted.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-unreadable.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-warning.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/emblems/24/emblem-web.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/status/16/numlock-disabled-symbolic.svg
> Error: Orphaned: share/icons/evolvere-blue-folders-flat-vivid/status/16/numlock-enabled-symbolic.svg

**Comment by newsiberian** [comment]
Frank, excuse me for my overniceness, but one icon still missed:
evolvere-blue-folders-flat-vivid/actions/16/ubuntustudio-publishing.svg

**Comment by franksouza183** [comment]
Oh, sorry, reopening...
