### ISSUE TITLE
Request icon: yandex-browser

### ISSUE THREAD

**Issue by ghost** [franksouza183/EvolvereSuit#104]
[Yandex Browser](https://browser.yandex.com/) is Yet Another Chromium Rebuild from Russia with love.
Official logo:
![Logo](http://delate.info/uploads/posts/2013-02/1360255406_846.jpg)
![Another logo](http://www.vladtime.ru/uploads/posts/2013-12/1386769038_yandex-brauzer.png)
![And Another](http://yamobi.ru/i/posts/rec013222/yabr_large.jpeg)

Like Chromium, this needs 3 additional symlinks to yandex-browser icon: yandex-browser-stable, yandex-browser-beta, yandex-browser-unstable.

// If you think what this logo looks like thong on the white ball, [you](http://ic.pics.livejournal.com/neryungrinec/19672569/32542/32542_original.jpg) [are](http://i.imgur.com/hTFQi.jpg) [not](http://ru.pistolety-pnevmaticheskie.ru/uploads/posts/2014-06/1402149650_stringi.jpeg) [alone](http://postpic4.me/images/1/9b9da9986f44c56040365dbf2ec962d01c93a72d.png)...

**Comment by franksouza183** [comment]
It really reminded me, and I love be "alone"

**Comment by ghost** [comment]
@franksouza183

> I love be "alone"

I, too. But sometimes we need at least one friend who thinks the same way.

**Comment by franksouza183** [comment]
I mean ... "[alone](http://postpic4.me/images/1/9b9da9986f44c56040365dbf2ec962d01c93a72d.png)" :feelsgood:

**Comment by ghost** [comment]
@franksouza183

> I mean ... "alone" :feelsgood:

LOL...

**Comment by franksouza183** [comment]
[Done.](https://github.com/franksouza183/Evolvere-Icons/blob/master/apps/64/yandex-browser.svg)
