### ISSUE TITLE
evolvere-flat-vivid-sunken-dark-fallback : Sound-contrl icon is not correct 

### ISSUE THREAD

**Issue by mcjoeng** [franksouza183/EvolvereSuit#108]
Look at my snapshot

![_003](https://cloud.githubusercontent.com/assets/10485304/6934110/fd4ddc58-d861-11e4-89e6-c05ba29c6964.png)

**Comment by franksouza183** [comment]
What environment? KDE or XFCE? Thanks for the feedback!

**Comment by mcjoeng** [comment]
Ubuntu 14.04 Unity

**Comment by franksouza183** [comment]
Try now

**Comment by mcjoeng** [comment]
It works .Thanks. I like the evolvere-flat-vivid-sunken-dark-light-fallback
