### ISSUE TITLE
Huge menubar icons appearing on gtk3 apps

### ISSUE THREAD

**Issue by will8211** [franksouza183/EvolvereSuit#128]
First of all, awesome icon theme!
I'm using Evolvere Dark Fallback from the ubuntu PPA on xubuntu 15.04. On some gtk3 apps (ex: File-Roller and Evince have problems, but gThumb is fine), some menubar icons (ex: "Find, "Add," "Open") are appearing as huge (256p).
Thanks!

![screenshot_2015-04-28_14-59-53](https://cloud.githubusercontent.com/assets/12148797/7364281/5450ebd4-edb7-11e4-9843-052757b38b28.png)
)

**Comment by franksouza183** [comment]
Hi @will8211 , please, check this: https://github.com/franksouza183/EvolvereSuit/issues/9

**Comment by will8211** [comment]
Thanks, didn't see that! Changing MinSize=257 to MinSize=8 in 
/usr/share/icons/[themename]/index.theme
worked for me!
