### ISSUE TITLE
kodi

### ISSUE THREAD

**Issue by ryanfelder** [franksouza183/EvolvereSuit#129]
Nobody seems to have made an icon theme with an icon for Kodi yet :(

Req.

**Comment by MichaelTiebesl** [comment]
Frank was the first person who made an icon for Kodi after i made a request for it.
Issues 28 was it. March 8

**Comment by ryanfelder** [comment]
Hm... it's still showing up as the default icon for me. I'll investigate and maybe post a screenshot when I get home.

**Comment by franksouza183** [comment]
https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere/apps/64/kodi.svg
