### ISSUE TITLE
icon request : audex

### ISSUE THREAD

**Issue by tamascsabi** [franksouza183/EvolvereSuit#130]
Audex icon

**Comment by ghost** [comment]
Edit this issue. Let it contain only one icon request.

And for other icons create new separate issues, one issue per missing icon.
17.05.2015 19:50 пользователь "tamascsabi" notifications@github.com
написал:

**Comment by franksouza183** [comment]
[bec180e80cf6abdfb015cd60929aa8f0c1bf6477](https://github.com/franksouza183/Evolvere-Icons/commit/bec180e80cf6abdfb015cd60929aa8f0c1bf6477)
