### ISSUE TITLE
Mail icon is not highlighted at the top (no bevel)

### ISSUE THREAD

**Issue by pofigoon** [franksouza183/EvolvereSuit#133]
I noticed that MAIL icon is slightly different from the others. Seems like it's missing a lightning effect ( a "bevel" ) at the top :

![kmail_icon](https://cloud.githubusercontent.com/assets/9394517/9105208/330785d6-3c1e-11e5-8f2f-35950445a115.png)

**Comment by ghost** [comment]
I do not see anything different. Maybe @franksouza183 can see something, when he will have some time.

**Comment by franksouza183** [comment]
Sorry for the delay in answering you, guys.
This icon represents a letter, and it makes no sense an envelope be as thick as the other icons.

Marking as invalid and closing. Thanks
