### ISSUE TITLE
Icon request: CSS mime type

### ISSUE THREAD

**Issue by gerardbm** [franksouza183/EvolvereSuit#135]
Hi. I'm glad I found your icons theme. It's the best, definitely.

I would like to have an icon for the CSS mime type. Actually, I've already created an icon following the same colour guidelines, so you can take it as a proposal if you think it's appropriate. 

![text-css](https://cloud.githubusercontent.com/assets/5253997/9831796/1a153cbc-5965-11e5-99fc-1bca23e58ff3.png)

Feel free to use it :-)

I share the SVG files: `text-css.svg` and `editable_text-css.svg` (the file called `editable_text-css.svg` has the text editable) → https://www.dropbox.com/sh/tt1ifj8qtq5ilmb/AACBLlam2libAFm-zBNcPICOa?dl=0

**Comment by franksouza183** [comment]
[Done](https://github.com/franksouza183/Evolvere-Icons/blob/master/mimetypes/64/text-css.svg). Thanks for this.
