### ISSUE TITLE
Disproportionately sized window controls icons

### ISSUE THREAD

**Issue by tarkant** [franksouza183/EvolvereSuit#136]
After installing the icons pack and applying it following the Gnome Tweak Tool, I ended up with the window controls buttons too big as you can see in the illustration joined.
**Running** **configuration** : 
Ubuntu Gnome 15.04 64-bit
GNOME Shell 3.14.4

If you need any additional information, please let me know.
![screenshot from 2015-10-01 10 35 23](https://cloud.githubusercontent.com/assets/2838520/10218326/f0d7ac9a-682d-11e5-889e-73459bcd56e3.png)

**Comment by pofigoon** [comment]
+1
This happens in all GTK applications even on KDE (Kubuntu 15.04)

**Comment by franksouza183** [comment]
Hello guys, workaround here: https://github.com/franksouza183/EvolvereSuit/issues/9

**Comment by ghost** [comment]
> +1
> This happens in all GTK applications even on KDE (Kubuntu 15.04)

Just use the script I pushed into repo a while ago.

**Comment by franksouza183** [comment]
Oh, I appreciate that! Thanks Agent Smith

**Comment by nexfwall** [comment]
I did not noticed how that crappy app pasted self-advertising. I'm sorry for that.
