### ISSUE TITLE
Where is the installation instruction?

### ISSUE THREAD

**Issue by wxguy** [franksouza183/EvolvereSuit#138]
I have cloned the repo. But I could not find any instructions on how to install the suit. I am on Arch Linux with Kde desktop. 

Any help is appreciated...

**Comment by ghost** [comment]
Hello @wxguy.

You can clone repo using `mkdir -p "~/.evolveresuit" && git clone https://github.com/franksouza183/EvolvereSuit ~/.evolveresuit/` terminal command and then go to `~/.evolveresuit/icons` folder using either dolphin or terminal application.

All directories in `icons` are icon packs. You can either create symlink for each folder to `~/.local/share/icons`(create that directory if it does not exist) or just make a copy.

**Comment by ghost** [comment]
I'll update install instructions later, when I'll have some time. And then close this issue.
