### ISSUE TITLE
Icon request: OneNote mime type

### ISSUE THREAD

**Issue by MarioZ** [franksouza183/EvolvereSuit#139]

**Comment by ghost** [comment]
I'm not sure that @franksouza183 will do update this icon pack ever.

**Comment by MarioZ** [comment]
That's sad :(
Does that mean no further progress will be done on this package?

**Comment by ghost** [comment]
> Does that mean no further progress will be done on this package?

We should ask @franksouza183 about this, not me.

**Comment by franksouza183** [comment]
I'm back from the dead. I hope you're alive and well too, @nexfwall.

**Comment by franksouza183** [comment]
on new repo
