### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hjri** [franksouza183/EvolvereSuit#140]
Subj.

**Comment by franksouza183** [comment]
This project is a hobby of mine, and unfortunately I do not have enough free time to keep it updated at the time. But dead? No. I'm using it right now. Working with development (my current occupation) in parallel with artwork explodes any mind already unbalanced like mine. If to consider some my project as dead, I would say it would be FS Icons but not Evolvere. FOSS rules, sorry :(

**Comment by hjri** [comment]
Thanks, just wanted to know, seeing such amazing iconpack falling silent for so long. Looking forward to possible future updates.
