### ISSUE TITLE
Some icons are not properly showed in panel

### ISSUE THREAD

**Issue by Flashwalker** [franksouza183/EvolvereSuit#145]
I'm using `evolvere-blue-folders-vivid-dark-fallback` variant.  
Few years ago it was good 
![original](https://user-images.githubusercontent.com/2188215/104795989-b2817580-57c3-11eb-9eac-c66b53b89bea.jpg)
 (openbox)  

But now it is not so good 
![Снимок экрана_2021-01-16_03-58-11](https://user-images.githubusercontent.com/2188215/104796013-dfce2380-57c3-11eb-9224-4c006244765e.png)
 (xfce)  

These wrong icons are: xfce4-power-manager plugin, xfce4-pulseaudio-plugin and xfce4 notification plugin  
As you can see they are not `fallback` variant

**Comment by franksouza183** [comment]
looks like the notification plugin is colorizing the icons now (that's the right way imo). There's nothing I can do about it ... I'll release the "dark" version has soon I finish adjusting the light one, that can help in some way if your environment is "one colorish"
