### ISSUE TITLE
icons for iceweasel icedove pycharm terminator

### ISSUE THREAD

**Issue by arkhan** [franksouza183/EvolvereSuit#15]
Could you please add this icon's

**Comment by franksouza183** [comment]
Of Course! Please open a new issue for each icon request, it will help to track each commit, and keep us organized. Thank U !! ;)

**Comment by arkhan** [comment]
ok thx

**Comment by franksouza183** [comment]
Oh, iceweasel has been done: https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken-dark-fallback/apps/64/Iceweasel.svg

**Comment by franksouza183** [comment]
If this is not being detected, please show me his .desktop file, this is perhaps hardcoded?
