### ISSUE TITLE
icon for radio tray

### ISSUE THREAD

**Issue by pled** [franksouza183/EvolvereSuit#20]
site : http://radiotray.sourceforge.net/

**Comment by franksouza183** [comment]
Already done: https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken/apps/64/radiotray.svg

Status icons:

https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken/status/22/radiotray_off.svg

https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken/status/22/radiotray_on.svg

Maybe hardcoded?
