### ISSUE TITLE
icons for Fcitx

### ISSUE THREAD

**Issue by mcjoeng** [franksouza183/EvolvereSuit#23]
Fcitx is a CJK input method framework (It's useful for Chinese users)

**Comment by franksouza183** [comment]
This one? https://wiki.archlinux.org/index.php/fcitx

**Comment by franksouza183** [comment]
Please post me the contents of associated .desktop file. Is there any extra icon for this application (tray, mimetypes, etc.)? If so, please open an issue for each of them, and if possible with a screenshot of the same, this will speed up the creation process, avoiding that I need to install the program to test.

Thanks!

**Comment by mcjoeng** [comment]
Official website ：https://fcitx-im.org/wiki/Fcitx

**Comment by franksouza183** [comment]
That is the app icon? https://fcitx-im.org/fcitx.png

**Comment by mcjoeng** [comment]
YES。It is the original icon

**Comment by franksouza183** [comment]
Ok, one more thing, please post to me the contents of the .desktop file

**Comment by franksouza183** [comment]
Nevermind, I got it ;)

**Comment by mcjoeng** [comment]
I find three .desktop at /usr/share/applications

**Comment by mcjoeng** [comment]
fcitx.desktop

[Desktop Entry]
Name=Fcitx
Name[de]=Fcitx
Name[es]=Fcitx
Name[ja]=Fcitx
Name[zh_CN]=Fcitx
Name[zh_TW]=Fcitx
Name[ko]=Fcitx
GenericName=Input Method
GenericName[de]=Eingabemethode
GenericName[es]=Método de entrada
GenericName[ja]=入力メソッド
GenericName[zh_CN]=输入法
GenericName[zh_TW]=輸入法
GenericName[ko]=입력 방법
Comment=Start Input Method
Comment[de]=Eingabemethode starten
Comment[ja]=入力メソッドを開始
Comment[zh_CN]=启动输入法
Comment[zh_TW]=啓動輸入法
Comment[ko]=입력기 시작
Exec=fcitx
Icon=fcitx
Terminal=false
Type=Application
Categories=System;Utility;X-SuSE-DesktopUtility;
StartupNotify=false
X-GNOME-AutoRestart=false
X-GNOME-Autostart-Notify=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false

**Comment by franksouza183** [comment]
Post all, no problem

**Comment by mcjoeng** [comment]
fcitx-configtool.desktop

[Desktop Entry]
Name=Fcitx Configuration
Name[de]=Fcitx Konfiguration
Name[ja]=Fcitx 設定
Name[zh_CN]=Fcitx 配置
Name[zh_TW]=Fcitx 設定
Name[ko]=Fcitx 설정
GenericName=Input Method Configuration
GenericName[de]=Konfiguration Eingabemethode
GenericName[ja]=入力メソッドの設定
GenericName[zh_CN]=输入法配置
GenericName[zh_TW]=輸入法設定
GenericName[ko]=입력기 설정
Comment=Change Fcitx Configuration
Comment[de]=Wechsel der Fcitx Konfiguration
Comment[ja]=Fcitx 設定を変更
Comment[zh_CN]=修改 Fcitx 配置
Comment[zh_TW]=修改 Fcitx 設定
Exec=fcitx-configtool
Icon=fcitx
MimeType=
Type=Application
Categories=System;SystemSetup;
X-KDE-StartupNotify=false
StartupNotify=false

**Comment by mcjoeng** [comment]
fcitx-skin-installer.desktop

[Desktop Entry]
MimeType=application/x-fskin;;
Name=Fcitx Skin Installer
Name[de]=Fcitx Skin Installer
Name[ja]=Fcitxスキンインストーラー
Name[zh_CN]=Fcitx 皮肤安装器
Name[zh_TW]=Fcitx 佈景安裝程式
Name[ko]=Fcitx 스킨 인스톨러
Comment=Installer Script for Fcitx Skin
Comment[de]=Installationsscript für Fcitx-Skins
Comment[ja]=Fcitxスキンのインストールスクリプト
Comment[zh_CN]=Fcitx 皮肤的安装器
Comment[zh_TW]=Fcitx 佈景主題安裝器文本
Comment[ko]=Fcitx 스킨을 위한 인스톨러 스크립터
Exec=fcitx-skin-installer %U
Icon=fcitx
Terminal=false
Type=Application
Categories=Utility;Utility;X-SuSE-DesktopUtility;
StartupNotify=false
X-GNOME-AutoRestart=false
X-GNOME-Autostart-Notify=false
X-KDE-StartupNotify=false
NoDisplay=true

**Comment by franksouza183** [comment]
Ok, thanks!
