### ISSUE TITLE
The font size affect the notifications icon of plasma-theme , look at my snapshot

### ISSUE THREAD

**Issue by mcjoeng** [franksouza183/EvolvereSuit#24]
When I set font size to 10 , it show the normal notifications-icon
![snapshot5](https://cloud.githubusercontent.com/assets/10485304/6498766/d74bbd1e-c32a-11e4-9482-f9a98962caae.png)
![snapshot4](https://cloud.githubusercontent.com/assets/10485304/6498770/dcd98c34-c32a-11e4-82cc-655701ac340b.png)

But when I set font size to 11 or more than 11 , it show the system-default icon
![snapshot6](https://cloud.githubusercontent.com/assets/10485304/6498772/e0dfcc26-c32a-11e4-9db5-423de8d18589.png)
![snapshot7](https://cloud.githubusercontent.com/assets/10485304/6498774/e83047bc-c32a-11e4-9c9a-f62ad720ba23.png)

**Comment by franksouza183** [comment]
Please, try this command:

`rm -rvf $HOME/.kde/cache-$HOSTNAME/*`

Select another theme from system settings >> apply, then select Evolvere Plasma theme again.

**Comment by franksouza183** [comment]
Or ALT + F2, then `quitapp plasma-desktop && plasma-desktop`

**Comment by mcjoeng** [comment]
It doesn't help after doing as what you said. I don't think it is the problem of cache. Because there is no problem using other plasma-theme when I change the font size

**Comment by franksouza183** [comment]
Ok, I'll check this soon
