### ISSUE TITLE
Icon request: Mirror Check

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#29]
Is it possible to have an icon for Mirror Check?
# !/bin/bash

[Desktop Entry]
Type=Application
Version=2.0
Name=Mirror-Check
Icon=mirror-check
Exec=/usr/bin/mirror-check --gui
Categories=Network;

![mirrorcheck](https://cloud.githubusercontent.com/assets/10792019/6500914/eca74ca6-c34c-11e4-85da-1127dca3120b.png)

**Comment by MichaelTiebesl** [comment]
Frank you can close this for me, they dont use it anymore as app but as script. Maybe for another OS it can be usefull what i don't know.

**Comment by franksouza183** [comment]
I can keep open, and treat it as low priority, no problem.
