### ISSUE TITLE
Icon request: Octopi Cache Cleaner

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#30]
Is it possible to have an icon for Octopi Cache Cleaner?

[Desktop Entry]
Name=Octopi CacheCleaner
Icon=octopi
Exec=octopi-cachecleaner
Terminal=false
Type=Application
Categories=GNOME;GTK;System;
# NotShowIn=GNOME;XFCE;LXDE;KDE;

StartupNotify=true

![chacecleaner](https://cloud.githubusercontent.com/assets/10792019/6500955/5d72aa16-c34d-11e4-9502-1be782fa7f7b.png)

The Octopi inside the green icon should be Yellow.

**Comment by franksouza183** [comment]
I can create a new icon for Octopi CacheCleaner, but you will have to manually change the _icon_ variable in .desktop file, ok?
