### ISSUE TITLE
Icon request: Octopi Notifier

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#31]
Is it possible to have an icon for Octopi Notifier?

[Desktop Entry]
Name=Octopi Notifier
Icon=octopi
Exec=octopi-notifier
Terminal=false
Type=Application
Categories=GNOME;GTK;System;
# NotShowIn=GNOME;XFCE;LXDE;KDE;

StartupNotify=true

![notifier](https://cloud.githubusercontent.com/assets/10792019/6500974/ae126006-c34d-11e4-9fa3-bfa9cd098893.png)

The Octopi inside the green icon should be Red.

**Comment by franksouza183** [comment]
As for #30 , you will have to manually change the icon variable in .desktop file

**Comment by MichaelTiebesl** [comment]
Is it possible to have the eyes "green" like the other icons. To make it more uniform?
Thanks

![snapshot2](https://cloud.githubusercontent.com/assets/10792019/6841574/73a2a1d0-d3c7-11e4-9672-2186dd28cf8e.png)

**Comment by franksouza183** [comment]
I tried, but the contrast was disturbing, try it yourself, put green eyes and see a monster born muaaahahahah

**Comment by MichaelTiebesl** [comment]
Lol....okay thanks anyway.
