### ISSUE TITLE
Qt designer Icon

### ISSUE THREAD

**Issue by Marchin** [franksouza183/EvolvereSuit#36]
https://lh6.googleusercontent.com/-ODbtQIDBakY/VP0K8kDm1kI/AAAAAAAAAvs/3eQsOpPQ1CQ/w992-h560-no/snapshot29.png

**Comment by franksouza183** [comment]
I could see the current icon?

**Comment by franksouza183** [comment]
[OFF] Now I understand why you asked about the dark theme ;)

**Comment by Marchin** [comment]
![snapshot30](https://cloud.githubusercontent.com/assets/11382943/6549285/2d6725be-c5ef-11e4-9c56-6739551a2cbf.png)

There is the Qt designer and alsa the Qt4 designer, by default they use the same icon, so there is no need to create a new one for this program.

And yep, i like dak themes haha

By the way, i'm having an issue with my network management applet, the icon doesn't change. Is not a problem of your theme because it happens with every theme, but i thought you may know how to solve it

**Comment by franksouza183** [comment]
Nice desktop!!! I love this!

Regarding the applet problem, what your plasma theme? Could you show me a screenshot?

**Comment by Marchin** [comment]
![snapshot31](https://cloud.githubusercontent.com/assets/11382943/6549380/d31d6be8-c5f0-11e4-812f-a7b12cc0785b.png)

Thanks! It wouldn't look so good without such a great icon theme ;)

I'm using the violet pastel theme mixed with some other themes. But the applet theme never worked on my system, maybe because i installed kde myself and missed something. It doesn't even work properly, it tells my intense of use of conection instead of strenght signal, but i think that's a problem of both the kernel and my wireless adapter.

**Comment by franksouza183** [comment]
Have you tried a cache clean up? `rm -rvf $HOME/.kde/cache-$HOSTNAME/*`, then, try to select a full theme, not a mix. Try out with Evolvere Plasma theme, just for testing purposes

**Comment by Marchin** [comment]
![snapshot32](https://cloud.githubusercontent.com/assets/11382943/6549510/38694c4a-c5f3-11e4-8e69-57695f273f39.png)

-Changed the theme
-Deleted the cache
-Logged out and logged back in

Still it doesn't work, maybe i should ask in the kde forums

**Comment by franksouza183** [comment]
Ok, final tests:

1 - Try to install the theme evolvere in `/usr/share/kde4/apps/desktoptheme/` (I don't know if the same in KDE 5);
Clear your cache and try re-select the theme.

2 - If not, back up the following files in `/usr/share/kde4/apps/desktoptheme/default/icons/` (again, I don't know if the same in KDE 5);

network.svgz
plasma-networkmanagement2.svgz
plasma-networkmanagement.svgz

And put the same files from evolvere theme folder.

If the attempt 1 doesn't works, but the second does, may be there a problem in icon lookup, or missing a icon on new KDE 5 framework (have you tried with breeze theme?), then I suggest seeking help in KDE Forum.

**Comment by Marchin** [comment]
I'm actually using KDE 4

It's weird but in my /usr/share/kde4 folder i only hace 2 folders (services and servicestype).

I followed the first method by creating the missing folder but it didn't work and i can't  follow the second method because of the missing folders.

I think I'll ask in the distro forum how to re-install KDE 4 and see if that works

**Comment by franksouza183** [comment]
I believe this is the problem, try to create the missing folder, here is mine: https://mega.co.nz/#!G8ZiRBID!9lA6rOhcYd9jwXp3S0I_6LiIbGmGfTv-Ce1ifgafU1c

**Comment by Marchin** [comment]
It seems that system settings doesn't detect that folder at all, it just reads my local folder.

Also my .kde4/share/desktoptheme/default folder is empty it just has an empty folder called "wallpapers"

I think i should re-install kde

**Comment by franksouza183** [comment]
Ok, please, keep me updated ;)

**Comment by Marchin** [comment]
I will :)

Thank you by the way, i really appreciate your time and efforts

**Comment by franksouza183** [comment]
You're welcome!
