### ISSUE TITLE
evolvere-blue-folders/index.theme: size is zero

### ISSUE THREAD

**Issue by newsiberian** [franksouza183/EvolvereSuit#4]
Hello, Frank. 
I,m sorry. It is blue.
File evolvere-blue-folders/index.theme has 0 Kb size.

**Comment by franksouza183** [comment]
Are you sure? All black variants seems ok, look:

https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-black-folders-dark-fallback/index.theme
https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-black-folders-vivid-dark-fallback/index.theme
https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-black-folders-vivid/index.theme
https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-black-folders/index.theme

Plase, try download again, and feedback me

**Comment by franksouza183** [comment]
Ok, I see now

**Comment by franksouza183** [comment]
Fixed ;)
