### ISSUE TITLE
Icon request - rlogo_icon

### ISSUE THREAD

**Issue by AlephAlpha** [franksouza183/EvolvereSuit#42]
Could you please add an icon for `rlogo_icon`? It's the icon for R programming language. 

Here is the desktop file:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=R
Comment=R software environment for statistical computing and graphics
Exec=R
Icon=rlogo_icon
Terminal=true
StartupNotify=false
Categories=Graphics;Science;Math;Education
```

And here is the website: http://www.r-project.org/

**Comment by franksouza183** [comment]
Please, could you show me the desktop file and the website of the app?

**Comment by franksouza183** [comment]
Nevermind, I got it, thanks ;)

**Comment by franksouza183** [comment]
[e9435b07c3403e81ed175b2bea976387dede2133](https://github.com/franksouza183/Evolvere-Icons/blob/c41f8bd592eb3a917888ff6fecf12b4a798341c5/apps/64/rlogo_icon.svg)
