### ISSUE TITLE
Icon request for Pale Moon Web Browser

### ISSUE THREAD

**Issue by beachgurl721** [franksouza183/EvolvereSuit#43]
Would like to have an icon for the Pale Moon Web Browser please.

Website is http://www.palemoon.org/

**Comment by franksouza183** [comment]
I hope you enjoy it:
https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-flat-vivid-sunken/apps/64/palemoon.svg

https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken/apps/64/palemoon.svg

https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere/apps/64/palemoon.svg

**Comment by beachgurl721** [comment]
Thank you!
