### ISSUE TITLE
symbolic links request for Corebird pantheon photos and the elementary's snap photobooth

### ISSUE THREAD

**Issue by sergioad** [franksouza183/EvolvereSuit#44]
Hello friends, I noted that there are many symlinks needed for Evolvere

1.- twitter - corebird
2.- cheese - accessories-camera
3.- shotwell / eog / ristretto - multimedia-photo-manager

I hope my info was usefull to you :smile:

**Comment by franksouza183** [comment]
@sergioad , please, separate in one icon request by issue. All will be done :feelsgood:

**Comment by franksouza183** [comment]
And, err, I didn't understand the purpose of this issue, could you give me more details?

**Comment by sergioad** [comment]
Of course, the Twitter icon will cover the Corebird application, a Twitter client wich uses decorations drawn by the client side, the Cheese icon will cover the applications camara icon used by Snap photobooth the eleentaryOS web' camera app to take photos / video and finally the shotwell icon will cover the multimedia photo manager iicons wich is used by pantheon photos a Shotwell fork

**Comment by sergioad** [comment]
BTW @franksouza183 I did not separated my issues because I taken one request per categories, for example the GNOME games suite symlinks and emmulators, the next ones will be separated

**Comment by franksouza183** [comment]
Each icon has a different design? If so, then you must separate in one icon request by issue. I know it will give a lot of work, but it is necessary to track commits created for each icon.

**Comment by franksouza183** [comment]
Corebird: will have its own icon;
Snap-photobooth: what's the icon name used for this app? "applications-camera" ?
Multimedia-photo: as above, what's the icon name used for this app?

**Comment by sergioad** [comment]
2.- yes
3.- as I said pantheon photos the elementary OS' shotwell

**Comment by sergioad** [comment]
@franksouza183 1.- thank you very much, I will be waiting for it
2.- yes, Snap photobooth uses it
3.- as I said before it is used by the elementaryOS' Shotwell fork named pantheon photos

**Comment by franksouza183** [comment]
2: Symlink will be added;
3: Shotwell already added wich it's linked to image-viewer: https://github.com/franksouza183/EvolvereSuit/blob/master/icons/evolvere-vivid-sunken/apps/64/image-viewer.svg

**Comment by sergioad** [comment]
@franksouza183 3.- them link image-viewer to multimedia-photo-manager please :smile:

**Comment by franksouza183** [comment]
Ok, pull it in a minute. ;)

**Comment by franksouza183** [comment]
Oh, don't forget, open a request also to corebird

**Comment by sergioad** [comment]
Ok :smile:
