### ISSUE TITLE
Evolvere icons are needed for the GNOME games suite

### ISSUE THREAD

**Issue by sergioad** [franksouza183/EvolvereSuit#45]
Hello friend I am here with another request, this time with a request for the awesome GNOME games suite, I will give you the exact icon names and their GNOME wiki where you will find everything about them including screenshots and even their original icons and a description of them

four-in-a-row = https://wiki.gnome.org/Apps/Four-in-a-row
five-or-more = https://wiki.gnome.org/Apps/Five%20or%20more
gbrainy = https://wiki.gnome.org/Apps/gbrainy
gnome-chess = https://wiki.gnome.org/Apps/Chess
gnome-klotski = https://wiki.gnome.org/Apps/Klotski
gnome-mahjongg = https://wiki.gnome.org/Apps/Mahjongg
gnome-mines = https://wiki.gnome.org/Apps/Mines
gnome-nibbles = https://wiki.gnome.org/Apps/Nibbles
gnome-robots = https://wiki.gnome.org/Apps/Robots
gnome-sudoku = https://wiki.gnome.org/Apps/Sudoku
gnome-tetravex = https://wiki.gnome.org/Apps/Tetravex
hitori = https://wiki.gnome.org/Apps/Hitori
lango = https://wiki.gnome.org/Apps/Iagno
lightsoff = https://wiki.gnome.org/Apps/Lightsoff
quadrapassel = https://wiki.gnome.org/Apps/Quadrapassel
sweel-foop = https://wiki.gnome.org/Apps/Swell%20Foop
tali = https://wiki.gnome.org/Apps/Tali

I hope see them all soon on my awesome SolydX and I hope you have a good day :smile: 
cheers from Zapopan Jalisco Mexico

**Comment by franksouza183** [comment]
Thanks for separate them!

**Comment by sergioad** [comment]
No problem :smile:
