### ISSUE TITLE
there are broken links

### ISSUE THREAD

**Issue by newsiberian** [franksouza183/EvolvereSuit#5]
Hello again.
Please check this image: http://s011.radikal.ru/i317/1502/ed/fc533a997cd2.jpg

**Comment by franksouza183** [comment]
Thanx for the feedback

Please, try this command:

`rm -rvf $HOME/.kde/cache-$HOSTNAME/*`

then select the theme again from system settings.

**Comment by newsiberian** [comment]
Yes, it's help. Thanks.

**Comment by franksouza183** [comment]
You're welcome!
