### ISSUE TITLE
Evolvere icons are needed for PCSX and PCSXR

### ISSUE THREAD

**Issue by sergioad** [franksouza183/EvolvereSuit#64]
An Evolvere icon is neede for PCSX / PCSXR,:this is a PlayStation emulator, the icon can be a playstation dualshock 2 over a blue background, the original PS logo over a grey background or the famous square X circle and triangle logo on a grey background.

Icon name = pcsx-icon with a symbolic link to pcsxr-icon

PCSX original icon
![pcsx-icon](https://cloud.githubusercontent.com/assets/5375145/6650721/ea8c0bdc-c9e6-11e4-9006-e3b79dd65cd3.png)

**Comment by franksouza183** [comment]
[commit 4ab29ece10698634e6c5cae2936559b093d2f654](https://github.com/franksouza183/Evolvere-Icons/commit/4ab29ece10698634e6c5cae2936559b093d2f654)
