### ISSUE TITLE
Evolvere icon is needed for PCSX2

### ISSUE THREAD

**Issue by sergioad** [franksouza183/EvolvereSuit#65]
An Evolvere icon is needed for PCSX2, a PlayStation 2 emulator: it's icon can be the blue PS2 logo on blue over a black background, the famous square circle triangle and x logo on a black background or the PS2's controller on a blue background

Icon name = pcsx2

**Comment by franksouza183** [comment]
[commit 4ab29ece10698634e6c5cae2936559b093d2f654](https://github.com/franksouza183/Evolvere-Icons/commit/4ab29ece10698634e6c5cae2936559b093d2f654)
