### ISSUE TITLE
[Request] Missing Icon 'Bomi Player'

### ISSUE THREAD

**Issue by abhishek-rawal** [franksouza183/EvolvereSuit#7]
First of all thanks for such an awesome icon-set. My KDE Tumbleweed desktop is not complete without Evolvere icons.

Bomi Player details :

[Desktop Entry]
Name=bomi
GenericName=Media Player
Comment=Play your media
Name[pl]=bomi
Name[es]=bomi
Name[de]=bomi
Name[ko]=보미
GenericName[pl]=Odtwarzacz filmów
GenericName[es]=Reproductor multimédia
GenericName[de]=Mediaplayer
Comment[pl]=Odtwarzaczaj filmy z bomi
Comment[es]=Reproduzca vídeos
Comment[de]=Spielt Medien ab
Exec=bomi --wake %u
Icon=bomi
StartupNotify=true
Terminal=false
Type=Application
Categories=Qt;AudioVideo;Player;Video;Audio;
MimeType=inode/directory;application/ogg;application/x-ogg;application/sdp;application/smil;application/x-smil;application/streamingmedia;application/x-streamingmedia;application/vnd.rn-realmedia;application/vnd.rn-realmedia-vbr;audio/aac;audio/x-aac;audio/m4a;audio/x-m4a;audio/mp1;audio/x-mp1;audio/mp2;audio/x-mp2;audio/mp3;audio/x-mp3;audio/mpeg;audio/x-mpeg;audio/mpegurl;audio/x-mpegurl;audio/mpg;audio/x-mpg;audio/rn-mpeg;audio/ogg;audio/scpls;audio/x-scpls;audio/vnd.rn-realaudio;audio/wav;audio/x-pn-windows-pcm;audio/x-realaudio;audio/x-pn-realaudio;audio/x-ms-wma;audio/x-pls;audio/x-wav;video/mpeg;video/x-mpeg;video/x-mpeg2;video/mp4;video/msvideo;video/x-msvideo;video/ogg;video/quicktime;video/vnd.rn-realvideo;video/x-ms-afs;video/x-ms-asf;video/x-ms-wmv;video/x-ms-wmx;video/x-ms-wvxvideo;video/x-avi;video/x-fli;video/x-flv;video/x-theora;video/x-matroska;video/webm;audio/x-flac;audio/x-vorbis+ogg;video/x-ogm+ogg;audio/x-shorten;audio/x-ape;audio/x-wavpack;audio/x-tta;audio/AMR;audio/ac3;video/mp2t;audio/flac;
X-KDE-Protocols=ftp,http,https,mms,rtmp,rtsp,sftp,smb

**Comment by franksouza183** [comment]
Thank you, will be done!

**Comment by franksouza183** [comment]
Done ;)

**Comment by abhishek-rawal** [comment]
That was fast.
Thanks!
