### ISSUE TITLE
Issue Evolvere Light Aurorae 

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#74]
Hey hello,
The menu icon in the left corner is not square. When i take the default (Breeze) for example it will be square. This is in plasma5.

Thanks

Not square:
![menu](https://cloud.githubusercontent.com/assets/10792019/6703668/d21de89a-cd79-11e4-9b7b-db9871d39a06.png)

Square:
![menu1](https://cloud.githubusercontent.com/assets/10792019/6703672/e2ea6432-cd79-11e4-8e30-b4f5cc556216.png)

**Comment by franksouza183** [comment]
Thanks! I'll check

**Comment by franksouza183** [comment]
Ok, I can reproduce this, checking as bug

**Comment by franksouza183** [comment]
While I do not fix this officially open the file ~/.local/share/aurorae/themes/EvolvereLightrc and change the value of "ButtonWidthMenu" variable from 16 to 22.

**Comment by franksouza183** [comment]
To reload kwin, ALT+F2 and run

`killall kwin_x11 && kwin_x11`

**Comment by MichaelTiebesl** [comment]
Thanks, it is okay now.

**Comment by franksouza183** [comment]
I'll keep this issue open until the new release with the fix. Thanks!
