### ISSUE TITLE
Symbolic link

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#75]
Hi there,

Before i got in Dolphin my folders with a image on it. After an update my folders are just plain blue. Also the desktop folder is plain now.

I know before there was an image on the default folders in home or i could change the image on the folder by clicking on the properties en then look for the image i want on it. Then after that i got a hidden file with the directory for that. It is not working anymore.

Thanks

![dolphin](https://cloud.githubusercontent.com/assets/10792019/6704342/0886895c-cd82-11e4-9ce7-4203afc1ef08.png)

**Comment by franksouza183** [comment]
Well, this does not seem a problem with the evolvere Icon theme. Have you tried with another icon theme? Try also delete .directory file contained in these folders, and re-set the icons for each.

**Comment by MichaelTiebesl** [comment]
Thanks Frank, With another icon theme it is the same i see. Sorry for that.  When i re-set the icons the .directory file inside becomes a folder with the correct image on it then. So there must be something else wrong.

**Comment by franksouza183** [comment]
You're welcome! ;)
