### ISSUE TITLE
Home category icon

### ISSUE THREAD

**Issue by Marchin** [franksouza183/EvolvereSuit#77]
Would you make an icon for this? plz (inside homerun launcher)

![snapshot32](https://cloud.githubusercontent.com/assets/11382943/6725106/9c44b2c6-cde2-11e4-93ac-c5001809254b.png)

**Comment by franksouza183** [comment]
This icon is obtained from your current plasma theme, not Evolvere. Your current plasma theme is probably picking up from default theme. If you are under KDE4, this can be found in /usr/share/kde4/apps/desktoptheme/default/toolbar-icons/go.svgz. Copy to your home folder, so you do not need to edit the original file. Copy to ~/.kde/share/apps/desktoptheme/default/toolbar-icons/go.svgz and edit it with Inkscape, replacing each size by the corresponding Evolvere icons.
