### ISSUE TITLE
evolverelight plasma theme symlink broken

### ISSUE THREAD

**Issue by mcjoeng** [franksouza183/EvolvereSuit#82]
symlink of plasma-networkmanagement2.svgz broken

**Comment by franksouza183** [comment]
I think not:

![Evolvere print](http://i.imgur.com/KlnEUsB.jpg)

Please give me more details about the problem

**Comment by mcjoeng** [comment]
![1](https://cloud.githubusercontent.com/assets/10485304/6745707/3e73adae-cef6-11e4-8b08-a1a65402fe19.png)

**Comment by mcjoeng** [comment]
The direction is not right . It directs to /media/franksouza/frank-souza/projetos/icones/evolvere/git/kde-plasma-themes/kde4/EvolvereLight/icons/plasma-networkmanagement.svgz
It looks like it is the direction of your system instead of my system.

**Comment by franksouza183** [comment]
Oh yeah, don't use Evolvere Light plasma theme yet, this is still under development, as you can see in the commit message "EvolvereLight plasma theme added (ultra beta XD)"

**Comment by franksouza183** [comment]
Off topic, what are the two applications after the Amarok in your taskbar?

**Comment by mcjoeng** [comment]
The first one is bcloud.
bcloud is file a storage and synchronization service created and managed by Baidu. It is the the most poppular file storage and synchronization service in China. But there is no official client for Linux .

https://github.com/LiuLang/bcloud

![3](https://cloud.githubusercontent.com/assets/10485304/6746657/45197c0e-cf07-11e4-8d55-e76dd47f2e0d.png)

**Comment by mcjoeng** [comment]
The second one is Deepin-music .A music player developed by chinese 
https://github.com/linuxdeepin/deepin-music

![4](https://cloud.githubusercontent.com/assets/10485304/6746741/66bfe78e-cf08-11e4-9151-8376a0217ab3.png)
![5](https://cloud.githubusercontent.com/assets/10485304/6746744/79610292-cf08-11e4-896a-f50584cb36ff.png)

**Comment by franksouza183** [comment]
[bcloud] You can open an icon request for it, there is a .desktop file (https://github.com/LiuLang/bcloud/blob/master/share/applications/bcloud.desktop), and evolvere can cover its icon
