### ISSUE TITLE
klipper icon for plasma: not match with icons theme

### ISSUE THREAD

**Issue by newsiberian** [franksouza183/EvolvereSuit#83]
Hello Frank. I discovered that we have a nice icon for klipper in icon set. It may be better to use it instead of scissors in both plasma themes?
![ev_plasma_klipper](https://cloud.githubusercontent.com/assets/11130487/6745294/2e18d2b4-ced7-11e4-8ff9-69daeee58175.jpeg)

p.s. Also, should we report you bugs about very early beta of plasma theme or for now this is not necessary?

**Comment by franksouza183** [comment]
Please refer to my comment here https://github.com/franksouza183/EvolvereSuit/issues/82#issuecomment-83904525

**Comment by franksouza183** [comment]
"p.s. Also, should we report you bugs about very early beta of plasma theme or for now this is not necessary?"

no need :smile:

**Comment by franksouza183** [comment]
Anyway, this bug report was useful, I had not noticed this detail, many thanks!

**Comment by franksouza183** [comment]
Done, I hope you like

**Comment by newsiberian** [comment]
Thank you, Frank, I like it and I hope other users will like new klipper too. Especially thank you for your quick response.

**Comment by franksouza183** [comment]
You're very welcome ;)
