### ISSUE TITLE
Request icon: folder-yadisk

### ISSUE THREAD

**Issue by ghost** [franksouza183/EvolvereSuit#88]
A icon for Yet Another Cloud Storage, called [Yandex Disk](https://disk.yandex.ru).
Yandex Disk uses UFO as it's logo. Here is some examples:
![Yandex Disk logo examples](http://img.artlebedev.com/everything/yandex/disk/process/yandex-disk-process-05.gif)
![Official logo](http://geeklab.ru/wp-content/uploads/2012/04/yandex-dick-1.jpg)
![Big one from official twitter account](https://pbs.twimg.com/profile_images/475923711170588674/XSRpYopv.png)

**Comment by franksouza183** [comment]
I love this logo

**Comment by franksouza183** [comment]
Added on new repo
