### ISSUE TITLE
No regular icons

### ISSUE THREAD

**Issue by MichaelTiebesl** [franksouza183/EvolvereSuit#96]
In "plank" i don't have the same format of icons. 
Here an example from Kmail and Quassel.
How can i fix this?

Thanks

![snapshot1](https://cloud.githubusercontent.com/assets/10792019/6841621/219d47ea-d3c8-11e4-987c-d67d054c83e9.png)

**Comment by franksouza183** [comment]
These icons are from plasma theme, what I do not understand is how they came to the Plank, I'll take a look on a VM with plasma 5. Could you check how is the .desktop files content of these launchers? I believe they are in /usr/share/applications

**Comment by MichaelTiebesl** [comment]
What i did was making my own "plank". I just add a panel and made it smaller. I just drop the icons from the launcher in the "plank". So it is just the regular icons what i always use.
